Tabula/Models/Board.cs
using System;
using System.Collections.Generic;

namespace ASP_Tabula.Models
{
    public class Board
    {
        // Board properties

        public int id { get; set; }
        public string name { get; set; }
        public types type { get; set; }
        public enum types
        {
            Personal = 0,
            Project = 1
        }
        public IReadOnlyCollection<List> lists { get; set; }
        public DateTime createdAt { get; set; }
    }
}

Tabula/Models/User.cs
using System;
using System.Collections.ObjectModel;

namespace ASP_Tabula.Models
{
    public class User
    {
        // User properties

        public int id { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public DateTime dateOfBirth { get; set; }
        public DateTime createdAt { get; set; }
        public ReadOnlyCollection<Board> boards { get; set; }
    }
}

Tabula/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using ASP_Tabula.DALs;
using ASP_Tabula.Models;
using ASP_Tabula.Containers;
using Nancy.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ASP_Tabula.Controllers
{
    public class CardController : Controller
    {
        // Card related methods & properties

        private readonly ILogger<CardController> _logger;
        private readonly IConfiguration config;

        static List currentList;
        static Card currentCard;
        static int currentBoardID;

        string errorMessage;

        private BoardContainer boardContainer { get; set; }
        private ListContainer listContainer { get; set; }
        private CardContainer cardContainer { get; set; }


        public CardController(ILogger<CardController> logger, IConfiguration config)
        {
            // Set container and config

            _logger = logger;
            this.config = config;

            boardContainer = new BoardContainer(new BoardDAL(config));
            listContainer = new ListContainer(new ListDAL(config));
            cardContainer = new CardContainer(new CardDAL(config));
        }


        public IActionResult ReorderCards(string json, int boardID, int userID)
        {
            // Reorder cards

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }

            currentBoardID = boardID;

            if (InValidJSON(json) || InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID))
            {
                // Invalid JSON, boardID or has no access to the board

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            json = UpdateJson(json);

            // JSON to list of JSLists

            List<JSList> JSLists = new JavaScriptSerializer().Deserialize<List<JSList>>(json);

            if (JSONToListUnSuccessful(JSLists.Count))
            {
                // Unable to create list of JSLists

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            ChangeOrderIDsInList(JSLists);

            // Board page

            return RedirectToAction("SetCurrentBoard", "Board", new { id = boardID });
        }


        private bool InValidJSON(string json)
        {
            try
            {
                // Valid JSON

                JToken.Parse(json);
                return false;
            }
            catch (JsonReaderException)
            {
                errorMessage = "Unable to change the card order, please try again.";
                return true;
            }
        }


        private string UpdateJson(string json)
        {
            // Removes parts from JSON

            string jsonV2 = json.Replace("allCardIDs", string.Empty);
            jsonV2 = jsonV2.Substring(4, jsonV2.Length - 4);
            jsonV2 = jsonV2.Remove(jsonV2.Length - 1);

            return jsonV2;
        }


        private bool JSONToListUnSuccessful(int count)
        {
            if (count < 1)
            {
                // Unable to create JSLists

                errorMessage = "Unable to change the card order, please try again.";
                return true;
            }
            else
            {
                return false;
            }
        }


        private void ChangeOrderIDsInList(List<JSList> JSLists)
        {
            foreach (JSList JSList in JSLists)
            {
                // Loop through every list and update the orderID

                for (int i = 0; i < JSList.cardIDs.Length; i++)
                {
                    cardContainer.EditCard(JSList.cardIDs[i], JSList.ID, JSList.cardOrderIDs[i], DateTime.Now);
                }
            }
        }


        public IActionResult Create(int boardID, int listID, int userID)
        {
            // Create card modal

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns create card modal

                currentBoardID = boardID;
                currentList = listContainer.GetList(listID);

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID) || InvalidAccessToList(userID))
                {
                    // Invalid boardID, no access to the board or list

                    return new EmptyResult();
                }

                // Return create card modal

                return PartialView("../User/Card/_CreateCard", currentList);
            }
        }


        public IActionResult View(int boardID, int listID, int cardID, int userID)
        {
            // View card modal 

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns edit card modal

                currentBoardID = boardID;
                currentList = listContainer.GetList(listID);
                currentCard = cardContainer.GetCard(cardID);

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID) || InvalidAccessToList(userID) || InvalidAccessToCard(userID))
                {
                    // Invalid boardID, no access to the board, list or card

                    return new EmptyResult();
                }

                ViewData["listName"] = currentList.name;

                // Return View card modal

                return PartialView("../User/Card/_ViewCard", currentCard);
            }
        }


        [ValidateAntiForgeryToken]
        public IActionResult CreateNewCard(string cardname, string description, string priority, DateTime deadline)
        {
            // Create new card

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (ValidCardnameCheck(cardname) || ValidPriorityCheck(priority))
            {
                // Invalid priority or cardname

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            description = SetDescription(description);

            CreateCard(cardname, description, priority, deadline);

            // Board page

            return RedirectToAction("SetCurrentBoard", "Board", new { id = currentBoardID });
        }

        
        private void CreateCard(string cardname, string description, string priority, DateTime deadline)
        {
            // Create card based on deadline

            int cardsCount = cardContainer.CountCards(currentList.id);

            if (deadline.Date.Year == 1)
            {
                cardContainer.CreateCard(currentList.id, cardsCount, cardname, description, priority, default, DateTime.Now);
            }
            else
            {
                cardContainer.CreateCard(currentList.id, cardsCount, cardname, description, priority, deadline, DateTime.Now);
            }
        }


        public IActionResult Edit(int boardID, int listID, int cardID, int userID)
        {
            // Edit card modal 

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns edit card modal

                currentBoardID = boardID;
                currentList = listContainer.GetList(listID);
                currentCard = cardContainer.GetCard(cardID);

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID) || InvalidAccessToList(userID) || InvalidAccessToCard(userID))
                {
                    // Invalid boardId, no access to the board, list or card

                    return new EmptyResult();
                }

                ViewData["listName"] = currentList.name;

                // Return edit card modal

                return PartialView("../User/Card/_EditCard", currentCard);
            }
        }


        [ValidateAntiForgeryToken]
        public IActionResult EditCurrentCard(string cardname, string description, string priority, DateTime deadline)
        {
            // Edit current card

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (ValidCardnameCheck(cardname) || CurrentCardnameCheck(cardname) || ValidPriorityCheck(priority))
            {
                // Invalid priority, cardname or priority

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            description = SetDescription(description);

            UpdateCard(cardname, description, priority, default);

            // Board page

            return RedirectToAction("SetCurrentBoard", "Board", new { id = currentBoardID });
        }


        private void UpdateCard(string cardname, string description, string priority, DateTime deadline)
        {
            // Edit card based on deadline

            if (deadline.Date.Year == 1)
            {
                cardContainer.EditCard(currentCard.id, currentCard.orderID, cardname, description, priority, default, DateTime.Now);
            }

Tabula/Controllers/UserController.cs
using System;
using System.Data;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using ASP_Tabula.DALs;
using ASP_Tabula.Models;
using ASP_Tabula.Containers;

namespace ASP_Tabula.Controllers
{
    public class UserController : Controller
    {
        // User related methods

        private readonly ILogger<UserController> _logger;
        private readonly IConfiguration config;

        private static User user { get; set; }

        private static List<Board> projectBoards { get; set; }
        private static Board personalBoard { get; set; }
        private static Board currentBoard { get; set; }

        string errorMessage;

        private UserContainer userContainer { get; set; }
        private BoardContainer boardContainer { get; set; }


        public UserController (ILogger<UserController> logger, IConfiguration config)
        {
            // Set containers and config

            _logger = logger;
            this.config = config;

            userContainer = new UserContainer(new UserDAL(config));
            boardContainer = new BoardContainer(new BoardDAL(config));
        }


        public IActionResult SetData(string emailUsername)
        {
            // Get userdata

            DataTable userData = userContainer.GetUserDetails(emailUsername);

            SetUser(userData);
            SetCookie();
            SeperateBoards();

            return RedirectToAction("Index");
        }


        private void SetUser(DataTable userData)
        {
            // Set userdata

            user = new User();
            user.id = Convert.ToInt32(userData.Rows[0]["ID"]);

            user.firstname = Convert.ToString(userData.Rows[0]["First_name"]);
            user.lastname = Convert.ToString(userData.Rows[0]["Last_name"]);
            user.username = Convert.ToString(userData.Rows[0]["Username"]);

            user.email = Convert.ToString(userData.Rows[0]["Email"]);
            user.dateOfBirth = Convert.ToDateTime(userData.Rows[0]["Date_of_birth"]);
            user.createdAt = Convert.ToDateTime(userData.Rows[0]["Created_at"]);

            user.boards = boardContainer.GetBoards(user.id).AsReadOnly();
        }


        private void SetCookie()
        {
            // Set cookie

            HttpContext.Session.SetString("isLoggedIn", "yes");
        }


        private void SeperateBoards()
        {
            // Seperates boards

            projectBoards = new List<Board>();
            personalBoard = new Board();

            foreach (Board board in user.boards)
            {
                if (board.type == Models.Board.types.Personal)
                {
                    personalBoard = board;
                }
                else if (board.type == Models.Board.types.Project)
                {
                    projectBoards.Add(board);
                }
            }
        }


        public IActionResult Index()
        {
            // Main page

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                // Redirects to login page

                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewData["username"] = user.firstname;
                ViewData["personalBoard"] = personalBoard;
                return View("Index", projectBoards);
            }
        }


        public IActionResult Board(int id)
        {
            // Set selected board

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                // Redirects to login page

                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Get userdetails

                if (InvalidAccessToBoard(id))
                {
                    // Unable to create array of ints

                    ModelState.AddModelError("error", errorMessage);

                    ViewData["personalBoard"] = personalBoard;
                    return View("Index", projectBoards);
                }

                return RedirectToAction("GetUserDetails", "Board", new { emailUsername = user.email, boardID = id });
            }
        }

        private bool InvalidAccessToBoard(int boardID)
        {
            if (!boardContainer.HasAccessToBoard(user.id, boardID))
            {
                // No access to the board

                errorMessage = "Access denied.";
                return true;
            }
            else
            {
                return false;
            }
        }


        public IActionResult Details()
        {
            // Main page

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                // Redirects to login page

                return RedirectToAction("Index", "Login");
            }
            else
            {
                return RedirectToAction("GetUserDetails", "Details", new { emailUsername = user.email } );
            }
        }


        public ActionResult Logout()
        {
            // Logout

            user = new User();
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Login");
        }
    }
}

Tabula/Views/User/Board.cshtml
@using ASP_Tabula.Models;

@{
    ViewData["Title"] = "Board";
    var userID = ViewData["UserID"];
}

@model Board

<link rel="stylesheet" type="text/css" href="~/css/board.css">
<link rel="stylesheet" type="text/css" href="~/css/modal.css">

<div class="text-center">
    @Html.ValidationMessage("error", "", new { @class = "text-danger" })
</div>

<div class="board-layout">
    <input type="hidden" id="userID" value="@userID" />

    <div>
        <div class="board-text">@Html.Raw(Model.name)</div>
        <div>
            <button id="createList" class="trigger"><i class="fa fa-plus" aria-hidden="true"></i>Create list</button>
        </div>
        <div>
            <button id="reorderLists" class="trigger"><i class="fa fa-bars" aria-hidden="true"></i>Reorder your lists</button>
        </div>
    </div>

    <div id='boardlists' class="board-lists">

        @{
            if (Model.lists.Count != 0)
            {
                int listcount = 0;
                int cardcount = 0;

                foreach (List list in Model.lists)
                {
                    int cards = 0;
                    <div>
                        <div>
                            <button id="@("createCard"+ listcount)" class="trigger"><i class="fa fa-plus" aria-hidden="true"></i>Create card</button>
                        </div>
                        <div id="@("list"+ listcount)" class="board-list trigger" ondrop="dropIt(event); ChangeOrderOfCards();" ondragover="allowDrop(event)">
                            <div class="list-title">
                                <div>
                                    @Html.Raw(list.name)
                                </div>

                                <div>
                                    <button id="@("vlist"+ listcount)"><i class="fa fa-folder-open" aria-hidden="true"></i></button>
                                </div>

                                <div>
                                    <button id="@("elist"+ listcount)"><i class="fa fa-ellipsis-h" aria-hidden="true"></i></button>
                                </div>

                                <div>
                                    <button id="@("dlist"+ listcount)"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                </div>

                                <input type="hidden" name="@("hiddenlistid"+ listcount)" value="@list.id">
                                <input type="hidden" name="@("hiddenlistorderid"+ listcount)" value="@list.orderID">
                            </div>

                            @if (list.cards.Count != 0)
                            {
                                @foreach (Card card in list.cards)
                                {
                                    <div id='@("ls" + listcount +"card"+ cards)' class="card" draggable="true" ondragstart="dragStart(event)">
                                        @Html.Raw(card.name)

                                        <input type="hidden" id="@("hiddencardid"+ cardcount)" value="@card.id">
                                        <input type="hidden" id="@("hiddencardorderid"+ cardcount)" value="@card.orderID">

                                        <div>
                                            <button id="@("vcard"+ cardcount)"><i class="fa fa-folder-open" aria-hidden="true"></i></button>
                                        </div>

                                        <div>
                                            <button id="@("ecard"+ cardcount)"><i class="fa fa-ellipsis-h" aria-hidden="true"></i></button>
                                        </div>

                                        <div>
                                            <button id="@("dcard"+ cardcount)"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                        </div>
                                    </div>

                                    cards++;
                                    cardcount++;
                                }
                            }
                        </div>
                    </div>
                    listcount++;
                }
            }

            @*<input type="hidden" name="userID" value="@userID">*@
        }
    </div>
    <div id="partial"></div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="~/lib/dragdropswap/dragdropswap.js" type="text/javascript"></script>
<script src="~/js/board.js" type="text/javascript"></script>

<script>
    let reorderListsUrl = '@Url.Action("Reorder", "List", new { boardID = Model.id })';
    let reorderCardsUrl = '@Url.Action("ReorderCards", "Card", new { boardID = Model.id})';

    let createListUrl = '@Url.Action("Create", "List", new { boardID = Model.id })';
    let createCardUrl = '@Url.Action("Create", "Card", new { boardID = Model.id })';
    let editListUrl =   '@Url.Action("Edit", "List", new { boardID = Model.id })';
    let editCardUrl =   '@Url.Action("Edit", "Card", new { boardID = Model.id })';
    let viewListUrl =   '@Url.Action("View", "List", new { boardID = Model.id })';
    let viewCardUrl =   '@Url.Action("View", "Card", new { boardID = Model.id })';
    let deleteListUrl = '@Url.Action("Delete", "List", new { boardID = Model.id })';
    let deleteCardUrl = '@Url.Action("Delete", "Card", new { boardID = Model.id })';

    SetClicks();
</script>

Tabula/Views/User/Details.cshtml
@{
    ViewData["Title"] = "Personal details";
}

@model User

<link rel="stylesheet" type="text/css" href="~/css/modal.css">

<div class="container col-md-12">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mt-5">
            <div class="text-center">
                @Html.ValidationMessage("error", "", new { @class = "text-danger" })
            </div>

            <div>
                <div>
                    <h2>Firstname</h2>
                </div>
                <div>
                    <span>@Model.firstname</span>
                </div>
            </div>

            <div>
                <div>
                    <h2>Lastname</h2>
                </div>
                <div>
                    <span>@Model.lastname</span>
                </div>
            </div>

            <div>
                <div>
                    <h2>Username</h2>
                </div>
                <div>
                    <span>@Model.username</span>
                </div>
            </div>

            <div>
                <div>
                    <h2>Email</h2>
                </div>
                <div>
                    <span>@Model.email</span>
                </div>
            </div>

            <div>
                <div>
                    <h2>Date of birth</h2>
                </div>
                <div>
                    <span>@Model.dateOfBirth.ToString("dd-MM-yyyy")</span>
                </div>
            </div>

            <div>
                <div>
                    <h2>Created at</h2>
                </div>
                <div>
                    <span>@Model.createdAt</span>
                </div>
            </div>

            <div>
                <div>
                    <button id="@("changeEmail")"><i class="fa fa-exchange" aria-hidden="true"></i>Change email</button>
                </div>
                <div>
                    <button id="@("changePassword")"><i class="fa fa-exchange" aria-hidden="true"></i>Change password</button>
                </div>
            </div>

            <div id="partial"></div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="~/js/user.js"></script>

<script>
    let changeEmailUrl =    '@Url.Action("ChangeEmail", "Details")';
    let changePasswordUrl = '@Url.Action("ChangePassword", "Details")';

    SetClicks();
</script>

Tabula/Views/User/Index.cshtml
@using ASP_Tabula.Models;

@{
    ViewData["Title"] = "Index";

    var username = ViewData["username"];
    Board personalBoard = ViewData["personalBoard"] as Board;
}

@model List<Board>

<div class="container col-md-12">
    <div class="row">
        <div class="col-md-2 mt-5">
            <div class="dropdown">
                <input type="checkbox" id="personalBoard-toggle">
                <label for="personalBoard-toggle">
                    <span class="symbol-custom-input">
                        <i id="personalIcon" class="fa fa-caret-down" aria-hidden="true"></i>
                        <i class="fa fa-user" aria-hidden="true"></i>
                    </span>
                    Personal board
                </label>
                <ul class="menuHidden">
                    <li><a href='@Url.Action("Board", "User", new { id = personalBoard.id })'>@Html.Raw(personalBoard.name)</a></li>
                </ul>
            </div>

            <div class="dropdown">
                <input type="checkbox" id="projectBoards-toggle">
                <label for="projectBoards-toggle">
                    <span class="symbol-custom-input">
                        <i id="projectIcon" class="fa fa-caret-down" aria-hidden="true"></i>
                        <i class="fa fa-users" aria-hidden="true"></i>
                    </span>
                    Project boards
                </label>
                <ul class="menuHidden">
                    @{
                        if (Model.Count != 0)
                        {
                            foreach (Board projectBoard in Model)
                            {
                                <li><a href='@Url.Action("Board", "User", new { board = projectBoard })'>@Html.Raw(projectBoard.name)</a></li>
                            }
                        }
                        else
                        {
                            <li><a href="javascript:void(0);">No project board to show!</a></li>
                        }
                    }
                </ul>
            </div>
        </div>
        <div class="col-md-8">

            <div class="text-center">
                @Html.ValidationMessage("error", "", new { @class = "text-danger" })
            </div>

            @{
                if (DateTime.Now.Hour >= 0 && DateTime.Now.Hour <= 12)
                {
                    <span>Good morning, @username !</span>
                }
                else if (DateTime.Now.Hour >= 12 && DateTime.Now.Hour <= 16)
                {
                    <span>Good afternoon, @username!</span>
                }
                else
                {
                    <span>Good evening, @username!</span>
                }
            }
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

<script src="~/js/user.js"></script>
<script>
    SetBoardsClick();
</script>