Tabula/Models/List.cs
using System;
using System.Collections.Generic;

namespace ASP_Tabula.Models
{
    public class List
    {
        // List properties

        public int id { get; set; }
        public int orderID { get; set; }
        public string name { get; set; }
        public IReadOnlyCollection<Card> cards { get; set; }
        public DateTime createdAt { get; set; }
        public DateTime updatedAt { get; set; }
    }
}

Tabula/Models/User.cs
using System;
using System.Collections.ObjectModel;

namespace ASP_Tabula.Models
{
    public class User
    {
        // User properties

        public int id { get; set; }
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public DateTime dateOfBirth { get; set; }
        public DateTime createdAt { get; set; }
        public ReadOnlyCollection<Board> boards { get; set; }
    }
}

Tabula/Controllers/ListController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using ASP_Tabula.DALs;
using ASP_Tabula.Models;
using ASP_Tabula.Containers;
using Nancy.Json;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ASP_Tabula.Controllers
{
    public class ListController : Controller
    {
        // List related methods & properties

        private readonly ILogger<ListController> _logger;
        private readonly IConfiguration config;

        static List currentList;
        static int currentBoardID;

        string errorMessage;

        private BoardContainer boardContainer { get; set; }
        private ListContainer listContainer { get; set; }
        private CardContainer cardContainer { get; set; }


        public ListController(ILogger<ListController> logger, IConfiguration config)
        {
            // Set container and config

            _logger = logger;
            this.config = config;

            boardContainer = new BoardContainer(new BoardDAL(config));
            listContainer = new ListContainer(new ListDAL(config));
            cardContainer = new CardContainer(new CardDAL(config));
        }


        public IActionResult Reorder(int boardID, int userID)
        {
            // Reorder lists modal

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns reorder lists modal

                currentBoardID = boardID;

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID))
                {
                    // Invalid boardID or no access to the board

                    return new EmptyResult();
                }

                List<List> boardLists = listContainer.GetLists(boardID);

                // Return reorder list modal

                return PartialView("../User/List/_ReorderLists", boardLists);
            }
        }


        [ValidateAntiForgeryToken]
        public IActionResult ReorderLists(string json)
        {
            // Reorder lists

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (InValidJSON(json))
            {
                // Invalid JSON

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            json = UpdateJson(json);

            int[] listIDs = new JavaScriptSerializer().Deserialize<int[]>(json);

            if (JSONToArrayUnSuccessful(listIDs.Length))
            {
                // Unable to create array of ints

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            // Reorder lists

            ChangeListOrderIDs(listIDs);

            // Board page

            return RedirectToAction("SetCurrentBoard", "Board", new { id = currentBoardID });
        }


        private bool InValidJSON(string json)
        {
            try
            {
                // Valid JSON

                JToken.Parse(json);
                return false;
            }
            catch (JsonReaderException)
            {
                errorMessage = "Unable to change the card order, please try again.";
                return true;
            }
        }


        private string UpdateJson(string json)
        {
            // Update JSON

            string jsonV2 = json.Replace("listIDs", string.Empty);
            jsonV2 = jsonV2.Substring(4, jsonV2.Length - 4);
            jsonV2 = jsonV2.Remove(jsonV2.Length - 1);

            return jsonV2;
        }


        private bool JSONToArrayUnSuccessful(int count)
        {
            if (count < 1)
            {
                // Unable to create array of ints

                errorMessage = "Unable to change the list order, please try again.";
                return true;
            }
            else
            {
                return false;
            }
        }


        private void ChangeListOrderIDs(int[] listIDs)
        {
            // Loop through all listsIDs

            for (int i = 0; i < listIDs.Length; i++)
            {
                // Update the orderID of the list

                listContainer.EditList(listIDs[i], i, DateTime.Now);
            }
        }


        public IActionResult View(int boardID, int listID, int userID)
        {
            // View list modal

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns edit list modal

                currentBoardID = boardID;
                currentList = listContainer.GetList(listID);

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID) || InvalidAccessToList(userID))
                {
                    // Invalid boardID, no access to the board or no access to the list

                    return new EmptyResult();
                }

                // Return View list modal

                return PartialView("../User/List/_ViewList", currentList);
            }
        }


        public IActionResult Create(int boardID, int userID)
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns create list modal

                currentList = new List();
                currentBoardID = boardID;

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID))
                {
                    // Invalid boardID or no access to the board

                    return new EmptyResult();
                }

                // Return create list modal

                return PartialView("../User/List/_CreateList");
            }
        }


        [ValidateAntiForgeryToken]
        public IActionResult CreateNewList(string listname)
        {
            // Create new list

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (ValidListnameCheck(listname))
            {
                // Invalid listname

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            int listsCount = listContainer.CountLists(currentBoardID);

            // Create list

            listContainer.CreateList(currentBoardID, listsCount, listname, DateTime.Now);

            // Board page

            return RedirectToAction("SetCurrentBoard", "Board", new { id = currentBoardID });
        }


        public IActionResult Edit(int boardID, int listID, int userID)
        {
            // Edit list modal

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns edit list modal

                currentBoardID = boardID;
                currentList = listContainer.GetList(listID);

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID) || InvalidAccessToList(userID))
                {
                    // Invalid boardID, no access to the board or no access to the list

                    return new EmptyResult();
                }

                // Return edit list modal

                return PartialView("../User/List/_EditList", currentList);
            }
        }


        [ValidateAntiForgeryToken]
        public IActionResult EditCurrentList(string listname)
        {
            // Edit current list

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if (ValidListnameCheck(listname) || CurrentListnameCheck(listname))
            {
                // Invalid listname

                return RedirectToAction("Fail", "Board", new { message = errorMessage });
            }

            // Edit list

            listContainer.EditList(currentList.id, currentList.orderID, listname, DateTime.Now);

            // Board page

            return RedirectToAction("SetCurrentBoard", "Board", new { id = currentBoardID });
        }


        public IActionResult Delete(int boardID, int listID, int userID)
        {
            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Returns delete list modal

                currentBoardID = boardID;
                currentList = listContainer.GetList(listID);

                if (InvalidBoardID(currentBoardID) || InvalidAccessToBoard(userID) || InvalidAccessToList(userID))
                {
                    // Invalid boardID, no access to the board or no access to the list

                    return new EmptyResult();
                }

                // Delete list modal

                return PartialView("../User/List/_DeleteList", currentList);
            }
        }


        [ValidateAntiForgeryToken]

Tabula/Controllers/UserController.cs
using System;
using System.Data;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using ASP_Tabula.DALs;
using ASP_Tabula.Models;
using ASP_Tabula.Containers;

namespace ASP_Tabula.Controllers
{
    public class UserController : Controller
    {
        // User related methods

        private readonly ILogger<UserController> _logger;
        private readonly IConfiguration config;

        private static User user { get; set; }

        private static List<Board> projectBoards { get; set; }
        private static Board personalBoard { get; set; }
        private static Board currentBoard { get; set; }

        string errorMessage;

        private UserContainer userContainer { get; set; }
        private BoardContainer boardContainer { get; set; }


        public UserController (ILogger<UserController> logger, IConfiguration config)
        {
            // Set containers and config

            _logger = logger;
            this.config = config;

            userContainer = new UserContainer(new UserDAL(config));
            boardContainer = new BoardContainer(new BoardDAL(config));
        }


        public IActionResult SetData(string emailUsername)
        {
            // Get userdata

            DataTable userData = userContainer.GetUserDetails(emailUsername);

            SetUser(userData);
            SetCookie();
            SeperateBoards();

            return RedirectToAction("Index");
        }


        private void SetUser(DataTable userData)
        {
            // Set userdata

            user = new User();
            user.id = Convert.ToInt32(userData.Rows[0]["ID"]);

            user.firstname = Convert.ToString(userData.Rows[0]["First_name"]);
            user.lastname = Convert.ToString(userData.Rows[0]["Last_name"]);
            user.username = Convert.ToString(userData.Rows[0]["Username"]);

            user.email = Convert.ToString(userData.Rows[0]["Email"]);
            user.dateOfBirth = Convert.ToDateTime(userData.Rows[0]["Date_of_birth"]);
            user.createdAt = Convert.ToDateTime(userData.Rows[0]["Created_at"]);

            user.boards = boardContainer.GetBoards(user.id).AsReadOnly();
        }


        private void SetCookie()
        {
            // Set cookie

            HttpContext.Session.SetString("isLoggedIn", "yes");
        }


        private void SeperateBoards()
        {
            // Seperates boards

            projectBoards = new List<Board>();
            personalBoard = new Board();

            foreach (Board board in user.boards)
            {
                if (board.type == Models.Board.types.Personal)
                {
                    personalBoard = board;
                }
                else if (board.type == Models.Board.types.Project)
                {
                    projectBoards.Add(board);
                }
            }
        }


        public IActionResult Index()
        {
            // Main page

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                // Redirects to login page

                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewData["username"] = user.firstname;
                ViewData["personalBoard"] = personalBoard;
                return View("Index", projectBoards);
            }
        }


        public IActionResult Board(int id)
        {
            // Set selected board

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                // Redirects to login page

                return RedirectToAction("Index", "Login");
            }
            else
            {
                // Get userdetails

                if (InvalidAccessToBoard(id))
                {
                    // Unable to create array of ints

                    ModelState.AddModelError("error", errorMessage);

                    ViewData["personalBoard"] = personalBoard;
                    return View("Index", projectBoards);
                }

                return RedirectToAction("GetUserDetails", "Board", new { emailUsername = user.email, boardID = id });
            }
        }

        private bool InvalidAccessToBoard(int boardID)
        {
            if (!boardContainer.HasAccessToBoard(user.id, boardID))
            {
                // No access to the board

                errorMessage = "Access denied.";
                return true;
            }
            else
            {
                return false;
            }
        }


        public IActionResult Details()
        {
            // Main page

            if (HttpContext.Session.GetString("isLoggedIn") == "" || HttpContext.Session.GetString("isLoggedIn") == null)
            {
                // Redirects to login page

                return RedirectToAction("Index", "Login");
            }
            else
            {
                return RedirectToAction("GetUserDetails", "Details", new { emailUsername = user.email } );
            }
        }


        public ActionResult Logout()
        {
            // Logout

            user = new User();
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Login");
        }
    }
}

Tabula/Views/User/List/_CreateList.cshtml
<link rel="stylesheet" type="text/css" href="~/css/form.css" />
<link rel="stylesheet" type="text/css" href="~/lib/animate/animate.css">
<link rel="stylesheet" type="text/css" href="~/lib/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

<div id="modal" class="modal open" data-modal="createList">
    <article class="content-wrapper">
        <button id="close" class="close"></button>
        <header class="modal-header">
            <h2>Add new list</h2>
        </header>
        <div class="content mt-3">
            <form class="custom-form validate-form" method="post" asp-controller="List" asp-action="CreateNewList">
                @Html.AntiForgeryToken()

                <div class="custom-wrap-input validate-input mt-3">
                    <input class="custom-input" type="text" minlength="2" name="listname" placeholder="Listname" required>
                    <span class="focus-custom-input"></span>
                    <span class="symbol-custom-input">
                        <i class="fa fa-list" aria-hidden="true"></i>
                    </span>
                </div>

                <footer>
                    <div class="container-form-btn">
                        <button class="custom-form-btn action">
                            Create list
                        </button>
                    </div>
                </footer>
            </form>
        </div>
    </article>
</div>

<script src="~/js/modal.js" type="text/javascript"></script>

Tabula/Views/User/List/_DeleteList.cshtml
<link rel="stylesheet" type="text/css" href="~/css/form.css" />
<link rel="stylesheet" type="text/css" href="~/lib/animate/animate.css">
<link rel="stylesheet" type="text/css" href="~/lib/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

<div id="modal" class="modal open" data-modal="deleteList">
    <article class="content-wrapper">
        <button id="close" class="close"></button>
        <header class="modal-header">
            <h2>Delete (@Model.name)</h2>
        </header>
        <div class="content mt-3">
            <form class="custom-form validate-form" method="post">
                @Html.AntiForgeryToken()

                <div class="text-center">
                    <div>
                        <span>Are you sure?</span>
                    </div>
                </div>

                <footer>
                    <div class="container-form-btn">
                        <button class="custom-form-btn action" asp-controller="List" asp-action="DeleteCurrentList">
                            Yes
                        </button>
                    </div>
                </footer>
            </form>
        </div>
    </article>
</div>

<script src="~/js/modal.js" type="text/javascript"></script>

Tabula/Views/User/List/_EditList.cshtml
<link rel="stylesheet" type="text/css" href="~/css/form.css" />
<link rel="stylesheet" type="text/css" href="~/lib/animate/animate.css">
<link rel="stylesheet" type="text/css" href="~/lib/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

@model List

<div id="modal" class="modal open" data-modal="editList">
    <article class="content-wrapper">
        <button id="close" class="close"></button>
        <header class="modal-header">
            <h2>Edit (@Model.name)</h2>
        </header>
        <div class="content mt-3">
            <form class="custom-form validate-form" method="post">
                @Html.AntiForgeryToken()

                <div class="text-center">
                    <div>
                        <h5>Created at:</h5>
                    </div>
                    <div>
                        <span>@Model.createdAt</span>
                    </div>
                </div>

                <div class="text-center">
                    <div>
                        <h5>Updated at:</h5>
                    </div>
                    <div>
                        <span>
                            @{
                                if (Model.updatedAt.Year == 1)
                                {
                                    <span>-</span>
                                }
                                else
                                {
                                    <span>@Model.updatedAt</span>
                                }
                            }
                        </span>
                    </div>
                </div>

                <div class="custom-wrap-input validate-input mt-3">
                    <input class="custom-input" type="text" minlength="2" name="listname" placeholder="Listname" value="@Model.name" required>
                    <span class="focus-custom-input"></span>
                    <span class="symbol-custom-input">
                        <i class="fa fa-list" aria-hidden="true"></i>
                    </span>
                </div>

                <footer>
                    <div class="container-form-btn">
                        <button class="custom-form-btn action" asp-controller="List" asp-action="EditCurrentList">
                            Edit list
                        </button>
                    </div>
                </footer>
            </form>
        </div>
    </article>
</div>

<script src="~/js/modal.js" type="text/javascript"></script>

Tabula/Views/User/List/_ReorderLists.cshtml
<link rel="stylesheet" type="text/css" href="~/css/form.css" />
<link rel="stylesheet" type="text/css" href="~/lib/animate/animate.css">
<link rel="stylesheet" type="text/css" href="~/lib/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

@model List<List>

<div id="modal" class="modal open" data-modal="reorderLists">
    <article class="content-wrapper">
        <button id="close" class="close"></button>
        <header class="modal-header">
            <h2>Reorder your lists</h2>
        </header>
        <div class="content mt-3">
            <form id="form" class="custom-form validate-form" onsubmit="reorderAllListsClick();" asp-controller="List" asp-action="ReorderLists">
                @Html.AntiForgeryToken()

                <ul id="listsOfCurrentBoard" class="custom-wrap-input validate-input text-center mt-3 sortable list">
                    @{
                        int count = 0;

                        foreach (List list in Model)
                        {
                            <div>
                                <li class="card">@list.name</li>
                                <input type="hidden" name="@("lOCBlistid"+ count)" value="@list.id">
                            </div>

                            count++;
                        }
                    }
                </ul>

                <input type="hidden" id="json" name="json">

                <footer>
                    <div class="container-form-btn">
                        <button id="reorderAllLists" class="custom-form-btn action">
                            Save
                        </button>
                    </div>
                </footer>
            </form>
        </div>
    </article>
</div>

<script src="~/lib/html5sortable/jquery.sortable.js" type="text/javascript"></script>
<script src="~/js/modal.js" type="text/javascript"></script>

<script>
    $(function () {
        $('.sortable').sortable();
        $('.handles').sortable({
            handle: 'span'
        });
        $('.connected').sortable({
            connectWith: '.connected'
        });
        $('.exclude').sortable({
            items: ':not(.disabled)'
        });
    });
</script>

Tabula/Views/User/List/_ViewList.cshtml
<link rel="stylesheet" type="text/css" href="~/css/form.css" />
<link rel="stylesheet" type="text/css" href="~/lib/animate/animate.css">
<link rel="stylesheet" type="text/css" href="~/lib/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

@model List

<div id="modal" class="modal open" data-modal="viewList">
    <article class="content-wrapper">
        <button id="close" class="close"></button>
        <header class="modal-header">
            <h2>View list (@Model.name)</h2>
        </header>
        <div class="content mt-3">
            <form class="custom-form validate-form">

                <div class="text-center">
                    <div>
                        <h5>Created at:</h5>
                    </div>
                    <div>
                        <span>@Model.createdAt</span>
                    </div>
                </div>

                <div class="text-center">
                    <div>
                        <h5>Updated at:</h5>
                    </div>
                    <div>
                        <span>
                            @{
                                if (Model.updatedAt.Year == 1)
                                {
                                    <span>-</span>
                                }
                                else
                                {
                                    <span>@Model.updatedAt</span>
                                }
                            }
                        </span>
                    </div>
                </div>

                <div class="custom-wrap-input validate-input mt-3">
                    <input class="custom-input" type="text" minlength="2" name="listname" placeholder="Listname" value="@Model.name" disabled>
                    <span class="focus-custom-input"></span>
                    <span class="symbol-custom-input">
                        <i class="fa fa-list" aria-hidden="true"></i>
                    </span>
                </div>
            </form>
        </div>
    </article>
</div>

<script src="~/js/modal.js" type="text/javascript"></script>